# Redirects
/filesafe/privacy_policy       /filesafe/privacy_policy.html
/smarttrashcan/privacy_policy   /smarttrashcan/privacy_policy.html
/zipmaster/privacy_policy       /zipmaster/privacy_policy.html
